# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: Pod
apiVersion: v1
metadata:
  name: indus-matchmaker-frontend
  namespace: indus-matchmaker
  labels:
    app: indus-matchmaker
    component: frontend
spec:
  containers:
  - name: indus-matchmaker-frontend
    # image: asia-south1-docker.pkg.dev/indus-staging-v1/linux-containers/indus-matchmaker-frontend:latest
    image: indus-matchmaker-frontend:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 51504
      name: indus-mm
  hostname: indus-matchmaker-frontend
---

kind: Service
apiVersion: v1
metadata:
  name: indus-matchmaker-frontend
  namespace: indus-matchmaker
spec:
  selector:
    app: indus-matchmaker
    component: frontend
  type: LoadBalancer
  ports:
  - port: 51504
    targetPort: indus-mm