apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
spec:
  containers:
  - name: nginx 
    image: nginx
    ports:
    - containerPort: 80

---

apiVersion: v1 
kind: Service
metadata:
  name: nginx-service  
spec:
  selector:
    app: nginx-test
  ports:
  - port: 80
    targetPort: 80
