apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: indus-gameserver-fleet-quads-2322
spec:
  replicas: 1
  scheduling: Packed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      generateName: "indus-gameserver-"
    spec:
      container: indus-gameserver
      ports:
      - name: default
        portPolicy: Passthrough
        container: indus-gameserver
        protocol: TCPUDP
      health:
        disabled: true
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
      sdkServer:
        logLevel: Info
        grpcPort: 9357
        httpPort: 9358
      template:
        metadata:
          labels:
            myspeciallabel: myspecialvalue
        spec:
          containers:
            - name: indus-gameserver
              image: asia-south1-docker.pkg.dev/indus-staging-mp/linux-containers/v0.32.115_2322
              imagePullPolicy: Always
              env:
              - name: SESSION
                value: "empty"
              - name: REGION
                value: "asia"
              - name: LOBBY
                value: "empty"
              - name: MODE
                value: "agones"
              - name: TEAM
                value: "2"
              - name: BOTS
                value: "60"
              - name: PORT
                value: "27015"
              - name: MASTER_CLIENT
                value: "1"
              - name: BOTS_FILLMODE
                value: "0"
              - name: MM
                value: "1"
              volumeMounts:
              - name: ca-cert-volume
                mountPath: /etc/ssl/certs/ca-certificates.crt
                subPath: ca-certificates.crt
          volumes:
          - name: ca-cert-volume
            configMap:
              name: ca-cert
              items:
              - key: ca-certificates.crt
                path: ca-certificates.crt
