name: Edit Config and Deploy to GKE - Development

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the release. Eg: 0.31.0_1735'
        required: true
      gamemodetype:
        description: 'Game Mode to Deploy'
        required: true
        type: choice
        options:
          - br
          - hotdrop
          - tutorial
          - tdm
      gamemodemap:
        description: 'Game Mode - Map to Deploy'
        required: true
        type: choice
        options:
          - br - virlok
          - hotdrop - foundry
          - hotdrop - lok terminal
          - tdm - refinery
      teamSize:
        description: 'Max Team Size'
        required: true
        type: choice
        options:
          - quads
          - duos
          - solos
      enableBots:
        description: 'Enable Bots Backfill'
        required: false
        type: boolean
        default: false
      botsBackfillLimit:
        description: 'Add Bots Backfill Limit'
        required: true
        default: '60'
      mm_mode:
        description: 'Enable Backend MM'
        required: true
        type: boolean
        default: true

run-name: Edit Config and Deploy to GKE - Dev - ${{ github.event.inputs.version }}
jobs:
  update_yaml:
    permissions:
      contents: 'write'
      id-token: 'write'
    name: Yaml Updater
    runs-on: ubuntu-latest
    steps:
    - name: Validate Version Format
      run: |
        VERSION_INPUT="${{ github.event.inputs.version }}"
        VERSION_REGEX="^[0-9]+\.[0-9]+\.[0-9]+_[0-9]+$"
        if [[ ! $VERSION_INPUT =~ $VERSION_REGEX ]]; then
          echo "Version format is invalid. Expected format: [number].[number].[number]_[number] (e.g., 0.31.0_1735)."
          exit 1
        fi
      shell: bash
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Delete Config
      run: rm Development/Agones/actionRunnerConfig.yaml

    - name: Copy File Content
      run: cp Development/Agones/actionRunnerConfigTemplate.yaml Development/Agones/actionRunnerConfig.yaml

# Fleet Name Updates

    - name: Replace _GAMEMODENAME_ in Fleet Name
      run: sed -i "s/_GAMEMODENAME_/${{github.event.inputs.gamemodetype}}/g" Development/Agones/actionRunnerConfig.yaml
      
    - name: Replace _GAMEMODEMAP_ in Fleet Name
      run: sed -i "s/_GAMEMODEMAP_/${{github.event.inputs.gamemodemap}}/g" Development/Agones/actionRunnerConfig.yaml
      
    - name: Replace _TEAMSIZENAME_ in Fleet Name
      if: github.event.inputs.gamemodetype == 'br' || github.event.inputs.gamemodetype == 'tdm'
      run: sed -i "s/_TEAMSIZENAME_/${{github.event.inputs.teamSize}}/g" Development/Agones/actionRunnerConfig.yaml

    - name: Replace _TEAMSIZENAME_ in Fleet Name
      if: github.event.inputs.gamemodetype == 'hotdrop'
      run: sed -i "s/_TEAMSIZENAME_/solo/g" Development/Agones/actionRunnerConfig.yaml

    - name: Replace _BUILD_NUMBER_ in Fleet Name
      run: |
          VERSION=$(echo "${{ github.event.inputs.version }}" | rev | cut -c 1-7 | rev)
          sed -i "s/_BUILD_NUMBER_/$VERSION/g" Development/Agones/actionRunnerConfig.yaml

# Build Version
      
    - name: Replace _VERSION_ in yaml template
      run: sed -i "s/_VERSION_/${{github.event.inputs.version}}/g" Development/Agones/actionRunnerConfig.yaml

# Env Variables

    - name: Replace _GAMEMODE_ in yaml template if BR
      if: github.event.inputs.gamemodetype == 'br'
      run: sed -i "s/_GAMEMODE_/0/g" Development/Agones/actionRunnerConfig.yaml

    - name: Replace _GAMEMODE_ in yaml template if hotdrop
      if: github.event.inputs.gamemodetype == 'hotdrop'
      run: sed -i "s/_GAMEMODE_/1/g" Development/Agones/actionRunnerConfig.yaml

    - name: Replace _GAMEMODE_ in yaml template if tdm
      if: github.event.inputs.gamemodetype == 'tutorial'
      run: sed -i "s/_GAMEMODE_/2/g" Development/Agones/actionRunnerConfig.yaml

    - name: Replace _GAMEMODE_ in yaml template if tdm
      if: github.event.inputs.gamemodetype == 'tdm'
      run: sed -i "s/_GAMEMODE_/3/g" Development/Agones/actionRunnerConfig.yaml
      

    - name: Replace _MAP_ in yaml template if BR - Virlok
      if: github.event.inputs.gamemodemap == 'br - virlok'
      run: sed -i "s/_MAP_/0/g" Development/Agones/actionRunnerConfig.yaml

    - name: Replace _MAP_ in yaml template if hotdrop - foundry
      if: github.event.inputs.gamemodemap == 'hotdrop - foundry'
      run: sed -i "s/_MAP_/1/g" Development/Agones/actionRunnerConfig.yaml

    - name: Replace _MAP_ in yaml template if hotdrop - lok terminal
      if: github.event.inputs.gamemodemap == 'hotdrop - lok terminal'
      run: sed -i "s/_MAP_/2/g" Development/Agones/actionRunnerConfig.yaml

    - name: Replace _MAP_ in yaml template if tdm - refinery
      if: github.event.inputs.gamemodemap == 'tdm - refinery'
      run: sed -i "s/_MAP_/3/g" Development/Agones/actionRunnerConfig.yaml



 
    - name: Replace _TEAM_SIZE_ in yaml template if QUADS
      if: github.event.inputs.teamSize == 'Quads' && (github.event.inputs.gamemodetype == 'br' || github.event.inputs.gamemodetype == 'tdm')
      run: sed -i "s/_TEAM_SIZE_/2/g" Development/Agones/actionRunnerConfig.yaml
      
    - name: Replace _TEAM_SIZE_ in yaml template if DUOS
      if: github.event.inputs.teamSize == 'Duos' && (github.event.inputs.gamemodetype == 'br' || github.event.inputs.gamemodetype == 'tdm')
      run: sed -i "s/_TEAM_SIZE_/1/g" Development/Agones/actionRunnerConfig.yaml

    - name: Replace _TEAM_SIZE_ in yaml template if SOLOs
      if: github.event.inputs.teamSize == 'Solos' && (github.event.inputs.gamemodetype == 'br' || github.event.inputs.gamemodetype == 'tdm')
      run: sed -i "s/_TEAM_SIZE_/0/g" Development/Agones/actionRunnerConfig.yaml

    - name: Replace _TEAM_SIZE_ in yaml template if hotdrop
      if: github.event.inputs.gamemodetype == 'hotdrop'
      run: sed -i "s/_TEAM_SIZE_/0/g" Development/Agones/actionRunnerConfig.yaml

      
    - name: Replace _BOTS_BACKFILL_ENABLE_ in yaml template if False
      if: ${{ github.event.inputs.enableBots == 'false' }}
      run: sed -i "s/_BOTS_BACKFILL_ENABLE_/0/g" Development/Agones/actionRunnerConfig.yaml

    - name: Replace _BOTS_BACKFILL_ENABLE_ in yaml template if True
      if: ${{ github.event.inputs.enableBots == 'true' }}
      run: sed -i "s/_BOTS_BACKFILL_ENABLE_/1/g" Development/Agones/actionRunnerConfig.yaml

    - name: Replace _BACKFILL_SIZE_ in yaml template
      run: sed -i "s/_BACKFILL_SIZE_/${{github.event.inputs.botsBackfillLimit}}/g" Development/Agones/actionRunnerConfig.yaml



    - name: Replace _MM_MODE_ in yaml template if False
      if: ${{ github.event.inputs.mm_mode == 'false' }}
      run: sed -i "s/_MM_MODE_/0/g" Development/Agones/actionRunnerConfig.yaml

    - name: Replace _MM_MODE_ in yaml template if True
      if: ${{ github.event.inputs.mm_mode == 'true' }}
      run: sed -i "s/_MM_MODE_/1/g" Development/Agones/actionRunnerConfig.yaml
      

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Development/Agones/actionRunnerConfig.yaml
        git commit -m "Update Development config in actionRunnerConfig.yaml"
        git push

# GCloud CLI Executions

    - name: GCP Cloud Auth
      id: 'gcp-cloud-auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY_DEV }}'
    - name: Create Service Account File
      uses: 'fertrig/create-file-action@1.0.2'
      with:
        file: 'GCP_SA.json'
        content: ${{ secrets.SERVICE_ACCOUNT_KEY_DEV }}
    - name: GKE Auth
      id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: 'agones-cluster'
        location: 'asia-south1-a'
      env:
        GOOGLE_APPLICATION_CREDENTIALS: 'GCP_SA.json'
    - id: 'get-pods'
      run: 'kubectl get fleets'
    - name: Apply the Configuration
      run: kubectl create -f https://raw.githubusercontent.com/JuneSoftware/icc/main/Development/Agones/actionRunnerConfig.yaml
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_DEV }}
