name: get secret

on:
  workflow_dispatch:
    inputs:
      version:
        description: none
        required: false

jobs:
  update_yaml:
    permissions:
      contents: 'write'
      id-token: 'write'
    name: secret
    runs-on: ubuntu-latest
    steps:
      - name: key
        run: 'echo "$KUBE_CONFIG_DATA" > key'
        shell: bash
        env:
          SSH_KEY: ${{secrets.KUBE_CONFIG_DATA }}
